### ISSUE TITLE
[Conversationgames] Error with wouldyourather

### ISSUE THREAD

**Issue by mrPauwHaan** [japandotorg/Seina-Cogs#21]
I am receiving the following error when running `[p]wouldyourather`

`Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/conversationgames/core.py", line 101, in _wyr
    result = await client._request("wyr", rating)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/conversationgames/http.py", line 94, in _request
    return await self.request("GET", f"/{endpoint}", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/conversationgames/http.py", line 61, in request
    return await self.__request(method, route, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/conversationgames/http.py", line 41, in __request
    cache = SQLiteBackend(
            ^^^^^^^^^^^^^^
  File "/data/cogs/Downloader/lib/aiohttp_client_cache/backends/__init__.py", line 23, in __init__
    raise original_exception
  File "/data/cogs/Downloader/lib/aiohttp_client_cache/backends/__init__.py", line 52, in <module>
    from aiohttp_client_cache.backends.sqlite import SQLiteBackend
  File "/data/cogs/Downloader/lib/aiohttp_client_cache/backends/sqlite.py", line 11, in <module>
    import aiosqlite
ModuleNotFoundError: No module named 'aiosqlite'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped`
` raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ModuleNotFoundError: No module named 'aiosqlite'`

**Comment by japandotorg** [comment]
@mrPauwHaan looks like pip failed to install `aiosqlite` when installing `aiohttp-client-cache`, you can try any of these -
1. `[p]pipinstall aiosqlite` - `[p]` is your bot's prefix.
2. `python -m pip install aiosqlite` in your bot's venv

**Comment by mrPauwHaan** [comment]
Thanks it works now 👍
