### ISSUE TITLE
playwire install chrome

### ISSUE THREAD

**Issue by fakesmile9704** [japandotorg/Seina-Cogs#23]
tried to use [p]screenshot with my instance. i saw that i need to run "playwire install chrome" but the issue is my device is arm
```Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/CogManager/cogs/seinatools/core.py", line 340, in _screenshot
    browser = await playwright.chromium.launch(channel="chrome")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/async_api/_generated.py", line 14340, in launch
    await self._impl_obj.launch(
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "playwright install chrome"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[5:27 PM]
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Error: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "playwright install chrome"```

```switching to root user to install dependencies...
++ arch
+ [[ aarch64 == \a\a\r\c\h\6\4 ]]
+ echo 'ERROR: not supported on Linux Arm64'
ERROR: not supported on Linux Arm64
+ exit 1
Failed to install browsers
Error: Failed to install chrome```

**Comment by fakesmile9704** [comment]
Another error when trying [p]spotify
```Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/CogManager/cogs/seinatools/core.py", line 447, in _spotify
    lambda pres: isinstance(pres, discord.Spotify), user.activities  # type: ignore
                                                    ^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'activities'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 783, in invoke
    await super().invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1647, in invoke
    await super().invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'User' object has no attribute 'activities'```

Wouldnt it be better to put up a error handler?

**Comment by japandotorg** [comment]
> tried to use [p]screenshot with my instance. i saw that i need to run "playwire install chrome" but the issue is my device is arm

Can you show me the exact command you ran for this?

**Comment by japandotorg** [comment]
> Another error when trying [p]spotify
That's one weird error, since activities is indeed a valid attribute for user, are you sure the user was in the server/shares server with the bot?

**Comment by fakesmile9704** [comment]
> That's one weird error, since activities is indeed a valid attribute for user, are you sure the user was in the server/shares server with the bot?

This is my fault for doing it in the dms cause i didnt realize i was making bot changes in the dm so nvm midn this

**Comment by fakesmile9704** [comment]
> 

i ran a simple on [p]ss https://www.udemy.com/course/the-python-mega-course/
and i got that error

**Comment by japandotorg** [comment]
> > 
> 
> i ran a simple on [p]ss https://www.udemy.com/course/the-python-mega-course/ and i got that error

Not that, the exact command you used to install chrome

**Comment by japandotorg** [comment]
> This is my fault for doing it in the dms cause i didnt realize i was making bot changes in the dm so nvm midn this

a `@commands.guild_only()` should fix that error

**Comment by fakesmile9704** [comment]
> > > 
> > 
> > 
> > i ran a simple on [p]ss https://www.udemy.com/course/the-python-mega-course/ and i got that error
> 
> Not that, the exact command you used to install chrome

`Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/CogManager/cogs/seinatools/core.py", line 340, in _screenshot
    browser = await playwright.chromium.launch(channel="chrome")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/async_api/_generated.py", line 14340, in launch
    await self._impl_obj.launch(
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "{HOME}/red/cogs/Downloader/lib/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "playwright install chrome"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Error: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "playwright install chrome"`
since this is the error so as it says i just run playwright install chrome but it is not available for arm

**Comment by fakesmile9704** [comment]
Lemon you can close this as it is not really related to the cog functionality. it is more of a achitecture issue.
I will look around and try to find a solution for this to fix and only i did i willl pr this or let you know about it.

**Comment by japandotorg** [comment]
Alright 👍🏼 , well either way I'll have to do something about this.
