### ISSUE TITLE
[DiscordPolls] Error when loading cog

### ISSUE THREAD

**Issue by Zoriot** [japandotorg/Seina-Cogs#61]
```Sep 25 00:02:24  python[2522761]: [2024-09-25 00:02:24] [WARNING] py.warnings: /home/zoriot/.local/share/Red-DiscordBot/data/Zoto/cogs/Downloader/lib/kaleido/scopes/base.py:188: DeprecationWarning:
Sep 25 00:02:24  python[2522761]: setDaemon() is deprecated, set the daemon attribute instead
Sep 25 00:05:00  python[2522761]: [2024-09-25 00:05:00] [WARNING] py.warnings: /home/zoriot/.local/share/Red-DiscordBot/data/Zoto/cogs/CogManager/cogs/discordpolls/_tagscript.py:88: TagScriptEngineAttributeRemovalWarning:
Sep 25 00:05:00  python[2522761]: Removal: EmbedBlock. (One of EmbedBlock's trait is scheduled to be removed in the next minor release, A minor exception handling which would restrict the embed from getting sent and would ra>
Sep 25 00:05:00  python[2522761]: [2024-09-25 00:05:00] [ERROR] red: Package loading failed
Sep 25 00:05:00  python[2522761]: Traceback (most recent call last):
Sep 25 00:05:00  python[2522761]:   File "/home/zoriot/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load
Sep 25 00:05:00  python[2522761]:     await bot.load_extension(spec)
Sep 25 00:05:00  python[2522761]:   File "/home/zoriot/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1684, in load_extension
Sep 25 00:05:00  python[2522761]:     lib = spec.loader.load_module()
Sep 25 00:05:00  python[2522761]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap_external>", line 1120, in load_module
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap_external>", line 945, in load_module
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap>", line 721, in _load
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Sep 25 00:05:00  python[2522761]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Sep 25 00:05:00  python[2522761]:   File "/home/zoriot/.local/share/Red-DiscordBot/data/Zoto/cogs/CogManager/cogs/discordpolls/__init__.py", line 27, in <module>
Sep 25 00:05:00  python[2522761]:     from .core import DiscordPolls
Sep 25 00:05:00  python[2522761]:   File "/home/zoriot/.local/share/Red-DiscordBot/data/Zoto/cogs/CogManager/cogs/discordpolls/core.py", line 48, in <module>
Sep 25 00:05:00  python[2522761]:     from .converters import PollAnswerConverter, PollConverter
Sep 25 00:05:00  python[2522761]:   File "/home/zoriot/.local/share/Red-DiscordBot/data/Zoto/cogs/CogManager/cogs/discordpolls/converters.py", line 30, in <module>
Sep 25 00:05:00  python[2522761]:     from emoji import EMOJI_DATA
Sep 25 00:05:00  python[2522761]: ModuleNotFoundError: No module named 'emoji'```

**Comment by japandotorg** [comment]
@Zoriot run `pip install emoji` in your venv

**Comment by Zoriot** [comment]
@japandotorg possible to mention that requirement anywhere? Maybe on readme or the discord messages when installing / addiing the repo

**Comment by japandotorg** [comment]
I'll add it to `info.json` so that downloader cog automatically installs that
